---
galaxy_info:
  author: Christopher Horrell
  description: Homebrew package management for macOS
  company: Horrell DevOps Consulting

  license: MPL-2.0

  min_ansible_version: "2.9"

  platforms:
    - name: MacOSX
      versions:
        - all

  galaxy_tags:
    - macos
    - homebrew
    - package
    - management

dependencies: []
collections:
  - community.general
